files/common/list.sh, src/networkBuilder.ts
=> Added reference to Readme

files/orchestrate/docker-compose.yml, templates/orchestrate/scripts/deps/docker-compose.yml
=> Remove Jaeger service

files/orchestrate/.env, files/orchestrate/README.md, files/orchestrate/docker-compose.yml, files/orchestrate/package.json, files/orchestrate/scripts/deps/config/hashicorp/Dockerfile, files/orchestrate/scripts/deps/config/hashicorp/config/config.hcl, files/orchestrate/scripts/deps/config/hashicorp/download-plugin.sh, files/orchestrate/scripts/deps/config/hashicorp/init.sh, files/orchestrate/scripts/deps/config/hashicorp/renew.sh, files/orchestrate/scripts/deps/config/hashicorp/vault.sh, files/orchestrate/src/create-faucet/app.ts, files/orchestrate/src/deploy-contract/deploy.ts, files/orchestrate/src/gasprice-retry/app.ts, files/orchestrate/src/generate-account/app.ts, files/orchestrate/src/get-accounts/app.ts, files/orchestrate/src/get-accounts/index.ts, files/orchestrate/src/register-chain/app.ts, files/orchestrate/src/register-contract/app.ts, files/orchestrate/src/send-tx/send-tx.ts, templates/orchestrate/scripts/deps/docker-compose.yml
Support for Orchestrate v21.1.0
=> Support Orchestrate v21.1.0

files/orchestrate/docker-compose.yml
- Update orchestrate image to v21.1.0
=> update orchestrate image

files/orchestrate/docker-compose.yml, orchestrate-image-manifest.json, templates/orchestrate/scripts/deps/docker-compose.yml
- Update Orchestrate image to v21.1.1 (missing manifest id update)
=> update orchestrate to v21.1.1

files/besu/README.md, files/gquorum/README.md
fix the image paths in the readme file
=> fix readme image paths

src/index.ts, src/questionRenderer.ts, src/questions/index.ts, templates/besu/config/besu/config.toml
add boot node question
add p2p discovery question
add node permissions question
add support for default config in answermap
add support for optional alternate no question tree in the yesnovalidator
=> Besu boot discovery node permissions

src/index.ts, src/questionRenderer.ts, src/questions/index.ts, templates/besu/config/besu/config.toml
Reverts ConsenSys/quorum-dev-quickstart#37
The questions are applicable to both Quourm and Besu, but the PR has only got content for Besu
=> Revert "Besu boot discovery node permissions"

files/besu/README.md, files/besu/smart_contracts/scripts/deploy.js, files/gquorum/README.md
the dapp directory to run the script and the account used were not mentioned.
=> update dapp instructions

files/orchestrate/docker-compose.yml, files/orchestrate/package.json, files/orchestrate/scripts/deps/hashicorp/config/agent-config.hcl, files/orchestrate/scripts/deps/hashicorp/config/config.hcl, package.json, templates/orchestrate/scripts/deps/docker-compose.yml
- bump orchestrate v21.1.4 
- integrate vault-agent token renewal
=> bump orchestrate v21.1.4 | integrate vault-agent token renewal

files/orchestrate/docker-compose.yml, files/orchestrate/package-lock.json, files/orchestrate/package.json
Reverts ConsenSys/quorum-dev-quickstart#76
needs the orchestrate manifest in here
=> Revert "Orchestrate v21.1.5"

files/orchestrate/package.json, files/orchestrate/src/send-eea-private-tx/app.ts, templates/besu/docker-compose.yml, templates/orchestrate/.env
- Remove Orion keys in favor of Tessera ones
- Exclude ethsigner container as it causes a dependency issue running Besu cluster
=> fixed orchestrate setup after latest network upgrades

files/besu/smart_contracts/scripts/private_tx.js, files/besu/smart_contracts/scripts/public_tx.js
Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>
=> [MINOR] make it easier to change the get/set number

files/besu/smart_contracts/package.json, files/besu/smart_contracts/scripts/concurrentPrivateTxs.js
Not sure if we want this - it does add another npm dependency but adds an interesting scenario for demoing.
Adapted from web3js-eea https://github.com/ConsenSys/web3js-eea/tree/master/example/concurrentPrivateTransactions
Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>
=> added concurrentPrivateTxs script for more exciting demo

README.md
Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>
=> updated readme to add splunk and correct cmd line

files/orchestrate/docker-compose.yml, files/orchestrate/package-lock.json, files/orchestrate/package.json, orchestrate-image-manifest.json, package.json
- Update to orchestrate version 21.1.6
=> update orchestrate version 21.1.6

files/common/remove.sh, files/common/run-blockscout.sh, npm-shrinkwrap.json, orchestrate-image-manifest.json, package.json, templates/besu/docker-compose.blockscout.yml, templates/besu/docker-compose.yml, templates/goquorum/docker-compose.blockscout.yml, templates/goquorum/docker-compose.yml
User request re blockscout as a monitoring tool, so adding this in. Doco to follow
=> adding the option of blockscout as a monitoring tool

npm-shrinkwrap.json, package.json, templates/besu/docker-compose.yml, templates/goquorum/docker-compose.yml
- updated blockscout version and apis that blockscout uses
=> updates for blockscout

files/goquorum/config/goquorum/docker-entrypoint.sh, files/goquorum/config/tessera/Dockerfile, files/goquorum/config/tessera/data/logback.xml, files/goquorum/config/tessera/data/tessera-config.json, files/goquorum/config/tessera/docker-entrypoint.sh, templates/goquorum/docker-compose.yml
Tidy up docker entrypoint for tessera - GoQuorum only
=> Tidy up docker entrypoint for tessera

files/orchestrate/package-lock.json
dependabot version deps issues
=> bump up dependency versions

files/goquorum/config/goquorum/docker-entrypoint.sh
fixes https://github.com/ConsenSys/quorum/issues/1356
=> Tidy up error messages

files/besu/quorum-explorer/config.json, files/goquorum/config/goquorum/Dockerfile, files/goquorum/config/goquorum/docker-entrypoint.sh, files/goquorum/quorum-explorer/config.json, npm-shrinkwrap.json, package.json, templates/besu/docker-compose.yml, templates/goquorum/docker-compose.yml
=> explorer updates and goq containers have user:group that isn't root

files/common/config/tessera/Dockerfile
https://github.com/ConsenSys/tessera/pull/1443
=> Develop base image has switched to ubuntu

files/besu/smart_contracts/privacy/scripts/concurrent_private_txs.js, files/besu/smart_contracts/privacy/scripts/keys.js, files/besu/smart_contracts/privacy/scripts/private_tx.js, files/besu/smart_contracts/privacy/scripts/private_tx_privacy_group.js, files/besu/smart_contracts/privacy/scripts/public_tx.js, files/common/.env, files/goquorum/smart_contracts/permissioning/scripts/deployEthers.js, files/goquorum/smart_contracts/privacy/scripts/keys.js, files/goquorum/smart_contracts/privacy/scripts/private_tx.js, files/goquorum/smart_contracts/privacy/scripts/public_tx.js, npm-shrinkwrap.json, package.json
Release to resolve https://github.com/ConsenSys/quorum-dev-quickstart/issues/183
Signed-off-by: Eric Lin <eric.lin@consensys.net>
=> update scripts to reflect changes to keys.js

npm-shrinkwrap.json, package.json, templates/besu/docker-compose.yml, templates/goquorum/docker-compose.yml
Signed-off-by: Eric Lin <eric.lin@consensys.net>
=> update explorer image and increment ver

npm-shrinkwrap.json, package.json, templates/besu/docker-compose.yml, templates/goquorum/docker-compose.yml
Signed-off-by: Eric Lin <eric.lin@consensys.net>
=> update explorer and increment ver

files/orchestrate/smart-contracts/Counter.sol
I believe it is meant to show `counter` , not `value`
=> Fix Counter.sol

files/common/config/tessera/data/tessera-config-template.json, files/goquorum/config/goquorum/data/qbft-enhanced-genesis.json, files/goquorum/config/goquorum/data/qbft-standard-genesis.json, files/goquorum/smart_contracts/privacy/scripts/private_tx.js
Add example of using privacyFlag in quick start
closes #243
=> Enable privacy enhancements on tessera and quorum by default

files/common/list.sh, files/common/sirato/5xx.html, files/common/sirato/nginx.conf, src/index.ts, src/networkBuilder.ts, src/questions/index.ts, templates/besu/docker-compose.yml, templates/goquorum/docker-compose.yml
Adds support for Sirato Blockchain Explorer by Web3 Labs.
Some screenshots - 
Questions -
List.sh output and containers -
Sirato -
=> Adds support for Sirato
